# Generated by Django 4.1.5 on 2023-01-15 19:58

from django.db import migrations, models
import image_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(help_text='Title of uploaded image. Field is using as a search parameter', max_length=32, verbose_name='Image title')),
                ('image_obj', models.ImageField(upload_to=image_api.models.get_image_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
